### ISSUE TITLE
Season From 2020 is out of scope of the valid seasons for this site. Will this be fixed?

### ISSUE THREAD

**Issue by gilbertkyle** [BrianDoucet01/daily-fantasy-sports#13]

**Comment by Brian-Doucet** [comment]
Hey Kyle,

**Comment by Brian-Doucet** [comment]
Hey Kyle,
Thanks for bringing this to my attention. I forgot the season had started already and I'll be working on updating this. The URL structure is a little different so it may take me a few days. I'll let you know when this is updated and I'll send out a new release.

**Comment by Brian-Doucet** [comment]
This has been fixed. Code updated to accept arguments for 2020 season. Please let me know if you have any issues. Just be sure to fetch all new changes.
