### ISSUE TITLE
games.get_game_data() is not working

### ISSUE THREAD

**Issue by subodh-thapa** [BrianDoucet01/daily-fantasy-sports#14]
games.get_game_data() function does not work with error message 'NoneType' object has no attribute 'text'.  I tried to download the data using cli.py and it has the same issue.

**Comment by Brian-Doucet** [comment]
Are you able to attach a screenshot so I can see how you're calling the program in your terminal?

**Comment by Brian-Doucet** [comment]
Are you trying to scrape 2020 season data?

**Comment by Brian-Doucet** [comment]
This has been fixed. Code has been updated to accept arguments for 2020 season.
